trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Checkout the repository
- task: Checkout@1
  displayName: 'Checkout Code'

# Debug Build Variables
- script: |
    echo "Debugging all available variables:"
    env | grep Build
  displayName: 'Debug Variables'

# Debug Source Directory
- script: |
    echo "Debugging the source directory:"
    echo "Listing all files in the source directory ($(Build.SourcesDirectory)):"
    ls -la $(Build.SourcesDirectory)
  displayName: 'Debug Source Directory'

# Debug Environment Variables
- script: |
    echo "Listing all available environment variables:"
    printenv
  displayName: 'Debug Environment Variables'

# Create Artifact Staging Directory
- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)
    echo "Artifact Staging Directory created at: $(Build.ArtifactStagingDirectory)"
  displayName: 'Create Artifact Staging Directory'

# Verify Static Files
- script: |
    echo "Checking for static files..."
    if [ -f "$(Build.SourcesDirectory)/calendar.html" ] && \
       [ -f "$(Build.SourcesDirectory)/calendar.js" ] && \
       [ -f "$(Build.SourcesDirectory)/styles.css" ]; then
      echo "All required static files found."
    else
      echo "One or more required static files are missing."
      exit 1
    fi
  displayName: 'Verify Static Files'

# Archive Static Files
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/static-$(Build.BuildId).zip'
  displayName: 'Archive Static Files'

# Publish Static Files as Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Static Files Artifact'