trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Checkout the repository
- task: Checkout@1
  displayName: 'Checkout Code'

# Debug source directory
- script: |
    echo "Debugging the source directory:"
    echo "Listing all files in the source directory ($(Build.SourcesDirectory)):"
    ls -la $(Build.SourcesDirectory)
  displayName: 'Debug Source Directory'

# Verify environment variables
- script: |
    echo "Listing all available environment variables:"
    printenv
  displayName: 'Debug Environment Variables'

# Verify static files exist
- script: |
    if [ -f "$(Build.SourcesDirectory)/calendar.html" ] && [ -f "$(Build.SourcesDirectory)/calendar.js" ] && [ -f "$(Build.SourcesDirectory)/styles.css" ]; then
      echo "All required static files found."
    else
      echo "One or more required static files are missing. Exiting with error."
      exit 1
    fi
  displayName: 'Verify Static Files'

# Archive static files
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/static-$(Build.BuildId).zip'
  displayName: 'Archive Static Files'

# Publish static files as artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Static Files Artifact'
