trigger:
- main  # Automatically triggers the pipeline on changes to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Specifies the agent pool

variables:
  buildConfiguration: 'Release'  # Define a variable for build configuration

steps:
- task: NodeTool@0  # Task to install a specific version of Node.js
  inputs:
    versionSpec: '16.x'  # Specify the Node.js version
    checkLatest: true

- script: |
    echo "Installing dependencies..."
    npm install  # Install dependencies from package.json
    echo "Dependencies installed."
  displayName: 'Install Dependencies'

- task: CopyFiles@2  # Task to copy application files to the build staging directory
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*'  # Copy all files in the directory
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1  # Task to publish build artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'