trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: echo "Starting build process..."
  displayName: 'Display Start Message'

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js 14.x'

- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'Run npm install'

- script: |
    npm run build
    echo "Build completed for $(buildConfiguration) configuration."
    ls -la $(Build.SourcesDirectory)
    ls -la $(Build.SourcesDirectory)/dist
  displayName: 'Run build and debug output'
  env:
    NODE_ENV: 'production'

- script: |
    if [ -d "$(Build.SourcesDirectory)/dist" ]; then
      echo "Dist directory exists."
    else
      echo "Dist directory does not exist. Exiting with error."
      exit 1
    fi
  displayName: 'Check for dist directory'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/build-$(Build.BuildId).zip'
  displayName: 'Archive build output'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifact'