trigger:
- main  # Trigger on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: echo "Pipeline started. Preparing to build JavaScript web application..."
  displayName: 'Starting Pipeline'

# Task 1: Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

# Task 2: Install dependencies using npm
- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'Install npm dependencies'

# Task 3: Build the JavaScript web application
- script: |
    npm run build
    echo "Build completed successfully for $(buildConfiguration) configuration."
  displayName: 'Build JavaScript Web Application'
  env:
    NODE_ENV: 'production'

# Task 4: Archive build output
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/build-$(Build.BuildId).zip'
  displayName: 'Archive Build Output'

# Task 5: Publish artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
