trigger:
- main  # Trigger the pipeline on commits to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Specify the virtual machine image

variables:
  buildConfiguration: 'Release'  # Define a variable for the build configuration

steps:
- script: echo "Starting build process..."
  displayName: 'Display Start Message'

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js 14.x'

- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'Run npm install'

- script: |
    npm run build
    echo "Build completed for $(buildConfiguration) configuration."
  displayName: 'Run build and display message'
  env:
    NODE_ENV: 'production'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/dist' 
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/build-$(Build.BuildId).zip'
  displayName: 'Archive build output'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifact'
