trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '14.x'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: 'npm run compile:sass'
  displayName: 'Compile Sass assets'
  workingDirectory: 'src'

- task: Gulp@1
  displayName: 'Run gulp tasks'
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 'build'
    arguments: '--configuration $(buildConfiguration)'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: 'src'

- script: 'npm run build'
  displayName: 'Build the project - Release'
  env:
    NODE_ENV: 'production'
